# Generated by Django 5.2.11 on 2026-02-13 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='details_demo',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
