# Generated by Django 5.2.11 on 2026-02-17 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_details_demo_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='details_demo',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
